name: bookmydoc2
description: "Book my Doctor - A healthcare app for booking doctors, managing appointments, and more."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # Core UI and Utilities
  cupertino_icons: ^1.0.8          # iOS-style icons for a polished look
  google_fonts: ^6.1.0            # Beautiful typography for text
  flutter_svg: ^2.0.10            # SVG support for icons and illustrations
  intl: ^0.20.2                   # Date/time formatting for appointments
  uuid: ^4.3.3                    # Generate unique IDs

  # State Management
  provider: ^6.1.2                # Lightweight state management

  # Navigation
  go_router: ^15.1.1              # Modern navigation with clean routing

  # UI Enhancements
  flutter_staggered_grid_view: ^0.7.0  # Dynamic grid layouts for doctor cards
  carousel_slider: ^5.0.0         # Carousel for recommended doctors or tips
  cached_network_image: ^3.3.1    # Efficient image loading with caching
  shimmer: ^3.0.0                 # Shimmer effect for loading states
  lottie: ^3.1.2                  # Lottie animations for a premium feel
  table_calendar: ^3.0.9          # Calendar for appointment booking/rescheduling
  flutter_rating_bar: ^4.0.1      # Rating bar for doctor reviews
  animate_do: ^4.2.0              # Smooth animations for widgets
  flutter_spinkit: ^5.2.1         # Variety of loading indicators
  chips_choice: ^3.0.1            # Filter chips for doctor search

  # Form Handling
  form_field_validator: ^1.1.0    # Form validation for sign-up/login

  # Notifications

  # Miscellaneous
  fluttertoast: ^8.2.12            # Attractive toast notifications
  url_launcher: ^6.2.6           # Open external links (e.g., clinic maps)
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  firebase_messaging: ^15.2.5
  file_picker: ^10.1.2  # For picking files like PDFs
  image_picker: ^1.1.2  # For picking images from gallery/camera
  google_sign_in: ^6.1.5
  firebase_storage: ^12.4.5
  permission_handler: ^11.3.0
  advance_pdf_viewer: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0           # Code quality and linting

flutter:
  uses-material-design: true
#  assets:
#    - assets/images/
#    - assets/icons/
#    - assets/lottie/
#
#  plugin:
#    platforms:
#      macos:
#        default_package: none
