// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdsgdPJxLVwVmrNUk17WkAGqny4WeGj8k',
    appId: '1:243386365194:web:cbbe65fae6bf7cd43176f3',
    messagingSenderId: '243386365194',
    projectId: 'bookmydoc2-8c00c',
    authDomain: 'bookmydoc2-8c00c.firebaseapp.com',
    storageBucket: 'bookmydoc2-8c00c.firebasestorage.app',
    measurementId: 'G-WLH3BT74TX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMNHN_r0CSg_pCIDdxdjbXkJl5kCRWMFE',
    appId: '1:243386365194:android:8468c018f1a6f0c33176f3',
    messagingSenderId: '243386365194',
    projectId: 'bookmydoc2-8c00c',
    storageBucket: 'bookmydoc2-8c00c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdsgdPJxLVwVmrNUk17WkAGqny4WeGj8k',
    appId: '1:243386365194:web:1d87b437028ef39e3176f3',
    messagingSenderId: '243386365194',
    projectId: 'bookmydoc2-8c00c',
    authDomain: 'bookmydoc2-8c00c.firebaseapp.com',
    storageBucket: 'bookmydoc2-8c00c.firebasestorage.app',
    measurementId: 'G-21HLRHBMS8',
  );
}
